# Generated by Django 3.2.6 on 2022-03-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReumeData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
